name: Publish to NPM
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: '7.9.5'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'pnpm'

      - name: Install dependencies and build 🔧
        run: pnpm i && pnpm build

      - name: Publish package on NPM 📦
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
